version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "80:80"
    command: ["npm", "run", "start"]
    restart: unless-stopped
    volumes:
      - /path/to/local/storage:/file-store
  db:
    image: postgres
    environment:
      POSTGRES_USER: not_cloud
      POSTGRES_PASSWORD: password
    ports:
      - "8001:5432"
    restart: unless-stopped